name: pf_dart_http
version: 1.0.0
description: >-
  Problem Fighter make a library for HTTP Request, Which is basically use of Dart HTTP package. The object of this library
  is use the dart http library with easy way with all combination such as POST, GET, PUT, DELETE, File upload etc,
  you may use the single file codes directly, without include this library.
homepage: https://github.com/problemfighter/pf-dart-http
documentation: https://hmtmcse.com/df-lib/easy/pf-dart-http
environment:
  sdk: '>=2.13.0 <3.0.0'
dependencies:
  http: ^0.13.3
dev_dependencies:
  test: '>=1.15.0 <2.0.0'